config/routes.rb
if Rails.env.development?
  Rails.application.routes.draw do
    get   '/time-machine' => 'dev_time/time_machine#show',
          as: :time_machine

    post  '/time-machine/travel' => 'dev_time/time_machine#travel',
          as: :time_machine_travel

    post  '/time-machine/return' => 'dev_time/time_machine#return',
          as: :time_machine_return
  end
end

app/controllers/dev_time/time_machine_controller.rb
if Rails.env.development?
  module DevTime
    class TimeMachineController < ApplicationController
      def show
        render layout: false
      end

      def travel
        if params[:destination].blank?
          flash[:time_machine_error] = "You must specify a destination time!"
        else
          begin
            Delorean.time_travel_to params[:destination]
            flash[:time_machine_message] = "Time travel successful."
          rescue => e
            flash[:time_machine_error] = "The Delorean wasn't able to understand your destination"
          end
        end
        redirect_to :time_machine
      end

      def return
        Delorean.back_to_the_present
        flash[:time_machine_message] = "You are safely back in the present."
        redirect_to :time_machine
      end
    end
  end
end

app/helpers/dev_time/current_time_helper.rb
module DevTime
  module CurrentTimeHelper
    def dev_time_stylesheet_link_tag
      if Rails.env.development?
        stylesheet_link_tag 'dev_time/current_time'
      else
        ''
      end
    end

    def dev_time_current_time_display
      if Rails.env.development? &&
         Delorean.send(:time_travel_offsets).any?
        content_tag :div, class: "dev-time-current-time" do
          "Time Travelling<br/>#{Time.now.strftime "%H:%M:%S %Y-%m-%d"}".html_safe
        end
      else
        ''
      end
    end
  end
end

app/views/dev_time/time_machine/show.html.erb
<html>
  <head>
    <title>DevTime Time Machine</title>
    <%= stylesheet_link_tag "dev-time" %>
  </head>
  <body>
    <h1>Welcome to the DevTime Time Machine</h1>
    <h3>powered by Delorean</h3>

    <div class="time-machine-dashboard">
      <div class="time-machine-readout">
        The time is now <%= Time.now.strftime "%H:%M:%S %Y-%m-%d" %>
      </div>

      <%- if flash[:time_machine_error].present? %>
        <div class="time-machine-error">
          <%= flash[:time_machine_error] %>
        </div>
      <% end %>

      <%- if flash[:time_machine_message].present? %>
        <div class="time-machine-message">
          <%= flash[:time_machine_message] %>
        </div>
      <% end %>
    </div>

    <div class="time-machine-controls">
      <%= form_tag time_machine_travel_path do %>
        Destination:
        <%= text_field_tag :destination %>
        <%= submit_tag "Travel through time!" %>
      <% end %>

      <%= form_tag time_machine_return_path do %>
        <%= submit_tag "Go back to the present!" %>
      <% end %>

      <p class="time-machine-instructions">
      The time machine understands many ways of talking about time.
      Both absolute (e.g. November 5, 1999) and
      relative (e.g. 3 years ago) will work.
      </p>

      <p class="time-machine-instructions">
      Note that if your development server checks for timeout (like
      Unicorn does) you may need to start it with a very long timeout
      setting (e.g. 1 year) in order to avoid having the worker killed
      while it is time travelling.
      </p>
    </div>
  </body>
</html>